import PptxGenJS from "pptxgenjs";
import type { PresentationWithSlides, ColorScheme } from "@/types";
import { COLOR_SCHEMES as colorSchemesData } from "@/types";

function getColorScheme(schemeId: string): ColorScheme {
  return colorSchemesData.find((s) => s.id === schemeId) || colorSchemesData[0];
}

export async function generatePptx(
  presentation: PresentationWithSlides,
  colorSchemeId: string = "blue"
): Promise<Blob> {
  const pptx = new PptxGenJS();
  const scheme = getColorScheme(colorSchemeId);

  pptx.layout = "LAYOUT_16x9";
  pptx.author = "EduSlide AI";
  pptx.company = "EduSlide AI";
  pptx.subject = presentation.title;
  pptx.title = presentation.title;

  const bgColor = scheme.background;
  const titleColor = scheme.primary;
  const textColor = scheme.text;
  const accentColor = scheme.accent;
  const primaryColor = scheme.secondary;

  const sortedSlides = [...presentation.slides].sort(
    (a, b) => a.slideNumber - b.slideNumber
  );

  for (const slide of sortedSlides) {
    const pptxSlide = pptx.addSlide();

    // Background
    pptxSlide.background = { color: bgColor };

    // Footer with page number
    pptxSlide.addText(`${presentation.title} | Slide ${slide.slideNumber}`, {
      x: 0.3,
      y: 6.9,
      w: 8.5,
      h: 0.3,
      fontSize: 8,
      color: "888888",
      align: "left",
    });

    pptxSlide.addText(`${slide.slideNumber} / ${sortedSlides.length}`, {
      x: 9,
      y: 6.9,
      w: 0.9,
      h: 0.3,
      fontSize: 8,
      color: "888888",
      align: "right",
    });

    if (slide.slideType === "title") {
      // Decorative accent bar
      pptxSlide.addShape(pptx.ShapeType.rect, {
        x: 0,
        y: 0,
        w: 10,
        h: 0.15,
        fill: { color: primaryColor },
        line: { color: primaryColor },
      });

      pptxSlide.addText(slide.title, {
        x: 0.8,
        y: 1.5,
        w: 8.4,
        h: 1.5,
        fontSize: 40,
        bold: true,
        color: titleColor,
        align: "center",
        breakLine: false,
      });

      if (slide.content && slide.content.length > 0) {
        pptxSlide.addText(slide.content.join(" | "), {
          x: 0.8,
          y: 3.2,
          w: 8.4,
          h: 0.8,
          fontSize: 20,
          color: textColor,
          align: "center",
        });
      }

      pptxSlide.addText("Generated by EduSlide AI", {
        x: 0.8,
        y: 4.5,
        w: 8.4,
        h: 0.4,
        fontSize: 12,
        color: "AAAAAA",
        align: "center",
        italic: true,
      });

      // Bottom accent
      pptxSlide.addShape(pptx.ShapeType.rect, {
        x: 0,
        y: 7.35,
        w: 10,
        h: 0.15,
        fill: { color: accentColor },
        line: { color: accentColor },
      });
    } else {
      // Header bar for non-title slides
      pptxSlide.addShape(pptx.ShapeType.rect, {
        x: 0,
        y: 0,
        w: 10,
        h: 1.1,
        fill: { color: primaryColor },
        line: { color: primaryColor },
      });

      // Slide type badge
      const slideTypeBadge = slide.slideType.toUpperCase();
      pptxSlide.addText(slideTypeBadge, {
        x: 0.3,
        y: 0.1,
        w: 2,
        h: 0.35,
        fontSize: 9,
        color: "FFFFFF",
        bold: true,
        align: "left",
      });

      // Slide title
      pptxSlide.addText(slide.title, {
        x: 0.3,
        y: 0.35,
        w: 9.4,
        h: 0.65,
        fontSize: 24,
        bold: true,
        color: "FFFFFF",
        align: "left",
      });

      // Content bullets
      if (slide.content && slide.content.length > 0) {
        const bulletItems = slide.content.map((item) => ({
          text: item,
          options: { bullet: true, color: textColor, fontSize: 16, paraSpaceAfter: 8 },
        }));

        pptxSlide.addText(bulletItems, {
          x: 0.4,
          y: 1.3,
          w: 9.2,
          h: 5.2,
          valign: "top",
          color: textColor,
          fontSize: 16,
        });
      }

      // Left accent line
      pptxSlide.addShape(pptx.ShapeType.rect, {
        x: 0,
        y: 1.1,
        w: 0.08,
        h: 5.8,
        fill: { color: accentColor },
        line: { color: accentColor },
      });
    }

    // Add speaker notes
    if (slide.speakerNotes) {
      pptxSlide.addNotes(slide.speakerNotes);
    }
  }

  return (await pptx.write({ outputType: "blob" })) as unknown as Blob;
}
